name: run tests on push
on: [push]
jobs:
  i-just-said-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm i
      - run: npm test
        env:
          CI: true